### ISSUE TITLE
Web: subtitles show in one row instead of two

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#101]
Ik zie opeens dat de boventitels die vroeger twee regels hadden nu op 1 regel achter elkaar gezet worden. Dit geeft problemen met lezen, zoals hier:

![screen shot 2015-05-31 at 10 31 07](https://cloud.githubusercontent.com/assets/12616308/7901291/61e8696a-0780-11e5-922e-c48de3495155.png)

dit lees je nu als 1 verwarrende zin. Kan dit terug gezet worden naar twee regels, of geeft dat problemen?

**Comment by MichelvanderAa** [comment]
in noodgeval moeten we komma's gaan zetten na de eerste regel op twee-regel-blokjes

**Comment by robbert** [comment]
![screen shot 2015-05-31 at 10 46 34](https://cloud.githubusercontent.com/assets/30694/7901330/c53a0d5a-0782-11e5-8346-87a840267b40.png)

There was no newline in the subtitles. I added one.

![screen shot 2015-05-31 at 10 49 24](https://cloud.githubusercontent.com/assets/30694/7901331/c9b8fa1c-0782-11e5-960c-28f085b59f89.png)

Fixed.

![screen shot 2015-05-31 at 10 52 03](https://cloud.githubusercontent.com/assets/30694/7901336/1aa7244e-0783-11e5-91af-8d8dd4bb7130.png)
