### ISSUE TITLE
Make mirror beta site available

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#105]
Can we make the beta site available again so we can check new code/bug fixes?

Also can you please remove the IP/Geoblock from this beta-site, Kate Miller-Heidke and the Sydney Festival would also like to check out the project and now can't because of the Geoblock ;-)

**Comment by robbert** [comment]
Fixed.

Beta site doesn't run on `/latest/` anymore, so just go to http://beta.bookofsand.nl/ -- that one has been available continuously.

thebookofsand.net

![screen shot 2015-06-01 at 13 26 18](https://cloud.githubusercontent.com/assets/30694/7911816/0483615c-0862-11e5-9aca-048fcb513d59.png)

beta.bookofsand.nl

![screen shot 2015-06-01 at 13 26 14](https://cloud.githubusercontent.com/assets/30694/7911822/0ed00ac0-0862-11e5-9f43-50dc8dc0c758.png)
