### ISSUE TITLE
Prepare a bunch of high-res stills for the press

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#106]
Press now use their own low-res screenshots, it would be better to create stills in the original quality.

Maybe add a "Press" page on the website for this purpose, or at least an "Download press kit" on the "About page". We should include the SVG logo as well.

**Comment by robbert** [comment]
We can use these as for screenshots in the app store as well, I suppose.

**Comment by MichelvanderAa** [comment]
ik heb HF een press kit gestuurd met stills vanmorgen

**Comment by robbert** [comment]
Mogen wij die press kit ook dan, i.v.m. screenshots voor app store.

**Comment by robbert** [comment]
Nevermind de press-kit, ik begrijp net van Yolijn dat jij in #66 hebt aangeboden om in de app de screenshots te maken.

**Comment by MichelvanderAa** [comment]
Ik heb je de link naar de press kit gisteren ook gemaild, hier:
http://www.dropbox.com/s/7xf5jthaf65ss7w/TheBookofSand_stills_graded_jpg.zip?dl=0

Maar ik zal de screenshot inderdaad maken. Verandert de interface niet meer grafisch?
