### ISSUE TITLE
Size of 'about' menu font

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#107]
When I look at the about menu with sort of fresh eyes I feel the font is slightly too large. Could you try making it one tiny step smaller on the beta site? Also maybe we could try to make the line space one tiny step smaller?

thx!

**Comment by MichelvanderAa** [comment]
I like it on the beta site, so lets implement on thebookofsand.net as well, thx!

**Comment by robbert** [comment]
Done.
