### ISSUE TITLE
SD and HD video quality - fine-tuning files and codec.

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#112]
I've done quite some research the last two days and asked around. My main findings:

- a lot of people don't notice the HD option because they're immediately immersed in video/interaction
- on a few people can manage stutter-free HD playback. It even stutters now and then on my fibre connection and fast mac.So I feel the HD option has too limited reach as it is now.

- I notice that we now use this video for SD playback: http://cdn.bookofsand.nl/MASTER+720x1098_GRADED_28mei.mp4
I thought that this resolution was only used on Internet Exporer?

I believe there a few things we can do to enhance quality and user experience:

- try replacing the SD playback with a higher-resolution but lower bitrate video. Like we did with the iOS video update. I think I can make a better looking file which is maybe 30-40 MB larger

- improving the HD buffering codec. There's still a few issues here, on Safari it sometimes keeps on loading/buffering for minutes and doesn't go back to playback.

- Should we forget about the partial buffering and force people to download the *entire* HD file first when they press 'HD' ? That way we're certain there won't be any bandwidth related stutters. We could add a message on screen saying "For seamless HD playback we need to load the HD file. This can take a few minutes. Please stay tuned!"

- try replacing the HD file with a smaller one. I will test with lower bit rates.

**Comment by robbert** [comment]
Internet Explorer uses `714x1088.mp4`, so the default SD quality video is OK.

**Comment by robbert** [comment]
Buffering the entire video in memory will crash most browsers, this cannot be done. When loading the three audio files in memory this already was a significant problem.

**Comment by MichelvanderAa** [comment]
ok that leaves the next options:

- optimising SD quality (Michel)
- lowering HD size (Michel
- optimising buffering code when switching to HD (Robbert)

**Comment by robbert** [comment]
Next week I'll be travelling by train for some time, because the WiFi connection is so erratic there that would be a great opportunity to tweak the buffering code.

**Comment by MichelvanderAa** [comment]
Lets use the smaller HD file on the main site as well:
https://s3-eu-west-1.amazonaws.com/betaofsand/MASTER+1280x1950_5000kbps_3juni.mp4

it's half the size of the current one and the differences are neglect-able if I compare the beta site and main site. Thanks!

**Comment by robbert** [comment]
Done.

What codec/bitrate settings did you end up using for both videos? Would love to have that information for future reference!

**Comment by MichelvanderAa** [comment]
Cool thanks. I couldn't improve the SD quality and keep a simular filesize. 

The trick for HD was to keep the resolution high and the bitrate low (2000kbps). Other than that I used the recommended settings by Vimeo and the slowest rendering speed
