### ISSUE TITLE
App v1.01 - buffering icon instead of play button at start-up

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#117]
![img_4314](https://cloud.githubusercontent.com/assets/12616308/7965663/39f20d3e-0a1f-11e5-88a4-19f936ebb2d5.PNG)

**Comment by robbert** [comment]
Non-blocking, I'd say. Swipe and other play button still work.

**Comment by robbert** [comment]
Fixed in 1.0.2.
