### ISSUE TITLE
Mouse cursor fade out together with navigator/controls

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#120]
It would be nice if the mouse cursor would fade out together with the navigator on in-activity. Now I find it's often in the way after using the navigator.  

It should then fade back in on new mouse movement.  Is that a hard thing to program...?

**Comment by robbert** [comment]
Fixed.

In Chrome and Safari on OS X the mouse cursor also hides when you press the arrow keys (even when the controls are visible still) -- but apparently this happens on all websites when you press keys that can cause the page to scroll.

**Comment by robbert** [comment]
By the way, it's only on thebookofsand.net -- I didn't update the beta.

**Comment by MichelvanderAa** [comment]
cool thx
