### ISSUE TITLE
Help / FAQ /support text

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#123]
Received quite a few frustrated responses of people that had trouble with the site and nowhere found a link to a help and/or support page

How much work would it be to create a fourth text page under 'about' with a simple FAQ; list of supported recommended browsers, solution for slow connection (press pauze and let it buffer for a while, etc)

I can supply the text, could you be so kind to add a menu? I realise you're way over your time and budget but I feel it would improve the experience for many users...

**Comment by MichelvanderAa** [comment]
I'll buy you dinner in a nice restaurant :-)

**Comment by robbert** [comment]
FAQ page is no problem at all, but the real question is: how to get to the 'about / credits / FAQ' when the website doesn't load and the splash screen is still in the way.

**Comment by MichelvanderAa** [comment]
I guess more people will have questions about stutters and or other interface issues than the stall on 75%. From what I've gathered only some Firefox users don't get past the loading screen...

**Comment by robbert** [comment]
Still want the FAQ page?

**Comment by MichelvanderAa** [comment]
Yes, I'll prepare a text. tbc

**Comment by MichelvanderAa** [comment]
ok hier is een opzet. kan je die eerst ff op de beta site zetten zodat we nog wat kunnen pielen met layout etc. Laten we het menu 'HELP' noemen. Voel je vrij om aan te vullen!
-----
HELP

—
Desktop or laptop computer

This website is build in HTML5 and works best in Google Chrome. Most residential cable and DSL connections should be more than adequate to playback this interactive video. In order to smoothly playback at HD quality you need at least a 20 Mbit/s download connection and a relatively current computer.

If you experience choppy video or audio playback;
• Press the ‘pause’ button and let the video buffer for a minute, then press ‘start’ again. 
• Close other browser tabs and windows. Close other applications.
• Make sure you use the most up-to-date version of your browser.

Known issues:
• Internet Explorer on Windows only works in standard video quality due to resolution restrictions set by Windows systems. 
• On some occasions FireFox stalls at 75% during the loading process. We’re working on a solution.
• If you switch between navigation with the mouse and the arrow keys the navigator could stop fading out on inactivity. You can solve this by clicking on one of the circles again and waiting for the navigator to fade out.


—
Mobile device

iOS
Please download our dedicated App from the AppStore (free)
-> download Appstore button

ANDROID & WINDOWS
Please use the mobile Google Chrome browser for the best experience


—
For further support please visit: (URL help pagina Holland Festival).

**Comment by MichelvanderAa** [comment]
when do you think you can do this..?

**Comment by mjeuk** [comment]
Done, staat nu op http://beta.bookofsand.nl/ als je tevreden bent kan hij live...!

**Comment by Yolijn** [comment]
`Done http://beta.bookofsand.nl/ als je tevreden bent kan hij live...!

**Comment by MichelvanderAa** [comment]
ok thx, paar kleine (layout) dingen:

- volgens mij staat de eerste regel lager dan op de andere tabs
- kan je de witregel weghalen tussen: "If you experience choppy video or audio playback:" en "Press the ‘pause’ button etc"
- dubbele punt achter "Known issues:"
- kan je de witregel weghalen tussen: "Known issues:" en "Internet Explorer on"
- kan je "google chrome" op eerste regel en slot tekst linken naar Chrome download pagina

daarna mag hij live!

**Comment by Yolijn** [comment]
Done! Layout dingen zijn gefixed, help pagina staat live!

**Comment by MichelvanderAa** [comment]
Super, dank!!!
