### ISSUE TITLE
Redundante hostnamen

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#124]
Google analytics geeft de volgende waarschuwing:
![screen shot 2015-06-16 at 20 35 28](https://cloud.githubusercontent.com/assets/12616308/8191257/5c7c9f5c-1467-11e5-8040-e023e1cb9aec.png)

Betekent dit dat niet al het bezoek gemeten wordt?

**Comment by robbert** [comment]
Fixed. Not sure about analytics. If you want to know if much has been missed by Google Analytics, maybe you can rummage through the Amazon S3 logs.

**Comment by robbert** [comment]
After some research I can conclude: redudant hostnames didn't affect the visitor statistics, all domains were being monitored.

**Comment by robbert** [comment]
That also means we don't have to analyse the S3 logs.

**Comment by MichelvanderAa** [comment]
ok good! (or bad because we can add counts...)
