### ISSUE TITLE
Fix AppStore logo / link on iOS landing page

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#125]
please remove the logo and place this sentence above a larger 'App Store' icon:

A dedicated 'Book of Sand' App can be downloaded via this button:

'Available on the App store' ICON (linking to the App store page)

**Comment by MichelvanderAa** [comment]
Every country of course has a different link/App store. Is there a way to always link to the users local Appstore?

**Comment by robbert** [comment]
The app store link you can use everywhere is:
https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=1000159198

The app store already makes an educated guess about what country you're in, and it's independent of the language of the store. My Mac is set to English, and Apple automatically shows me the Dutch App Store with English pages.

Thanks @Yolijn for fixing this.

**Comment by MichelvanderAa** [comment]
thanks, but the Icon is way too small now on an iOS screen. Can you make it 2 or 3 times bigger? Perhaps the same width as the BOS logo

**Comment by robbert** [comment]
Oops! Fixed now. Logo is clickable too now.

![img_1318](https://cloud.githubusercontent.com/assets/30694/8205756/d1cb320a-14f3-11e5-9a9d-e9669ad46e4a.PNG)

**Comment by MichelvanderAa** [comment]
where can I check the download stats for the App?
