### ISSUE TITLE
Icons scale differently on Safari, don't look as good...

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#14]

**Comment by robbert** [comment]
Please add a screenshot, works on my PC.

**Comment by MichelvanderAa** [comment]
![screen shot 2015-05-26 at 23 08 49](https://cloud.githubusercontent.com/assets/12616308/7823545/7bee4c58-03fc-11e5-8fc7-deed85296ca6.png)

**Comment by robbert** [comment]
![screen shot 2015-05-27 at 01 42 08](https://cloud.githubusercontent.com/assets/30694/7825803/a87d0998-0411-11e5-8362-a5e69ef38694.png)

**Comment by Grrr-Josephine** [comment]
Detail: We experience (on Google Chrome) that sometimes (not a lot) the buttons get stuck.
- Pause displayed instead of Play, when it's in pause.
- Full screen displayed instead of small screen when it's full screen.
