### ISSUE TITLE
Mouse-over text for icons to explain function?

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#15]

**Comment by Yolijn** [comment]
Added browser tooltip, isn't really pretty but gives user at least some feedback if needed. No real room on laptop screens for pretty tooltip anyway. On the plus side: Browsers have built in logic to display tooltip partly outside the browser window if there is too little room, not overlap the button and to show it only after a certain delay, but then showing it quickly when moving the mouse cursor to another button.
