### ISSUE TITLE
Michel: make different colour version of video for Chrome

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#17]

**Comment by MichelvanderAa** [comment]
Here's the video with a gamma fix for Chrome
http://youtu.be/9do_IjOOm3g

**Comment by robbert** [comment]
The switch is in.

**Comment by MichelvanderAa** [comment]
Thanks. Colours still don't match very well in my last render so I need make a new one.

I found that Safari is the only browser that shows the correct colour. Both Chrome and FireFox darken the colour and shift the reds.   

I think in the end we'll have to use one link for Safari (original) and a newly rendered edit for the rest of the browsers. 
to be continued...

**Comment by robbert** [comment]
Sound plausible because Safari is, as far as I know, the only browser to support ColorSync on OS X.
https://en.wikipedia.org/wiki/ColorSync

**Comment by MichelvanderAa** [comment]
not needed anymore, colour is much more consistent via Vimeo
