### ISSUE TITLE
Credit change

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#18]
Biennale Musiques en Scène Lyon 

moet worden:

Grame / Biennale Musiques en Scène Lyon

**Comment by robbert** [comment]
Misschien ook wel aardig om bij Grrr de designers bij naam te noemen.
![screen shot 2015-05-26 at 22 30 51](https://cloud.githubusercontent.com/assets/30694/7822589/e6f9b09c-03f6-11e5-9b1b-cada0bede452.png)

**Comment by robbert** [comment]
Fixed.

**Comment by MichelvanderAa** [comment]
Ja prima, maar volgens mij heeft Josephine de lead gehad in design, dus die misschien eerst noemen
