### ISSUE TITLE
Replace Quality icon with HD icon. Start-up in 'auto' quality, HD icon switches to highest quality. 

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#19]

**Comment by robbert** [comment]
![screen shot 2015-05-27 at 01 39 02](https://cloud.githubusercontent.com/assets/30694/7825757/33b48bea-0411-11e5-9026-e1e80836a7fc.png)


Instead of starting with "auto" I start with quality "large" (at 0.6 on a scale from 0.0 - 1.0) because auto looks way too shitty.

**Comment by MichelvanderAa** [comment]
Nice!
But I feel we need to get visual feedback if we switched to HD by leaving the inside of the HD icon grey. Otherwise we don't know what quality we're in. (see functionality Vimeo)

**Comment by robbert** [comment]
![screen shot 2015-05-27 at 09 32 41](https://cloud.githubusercontent.com/assets/30694/7831062/5f896c9e-0453-11e5-85a7-45221fecff5b.png)
