### ISSUE TITLE
Add logo of commissioners to 'about' page

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#2]

**Comment by robbert** [comment]
I'm pretty sure the designer isn't gonna like this.

![screen shot 2015-05-27 at 02 47 08](https://cloud.githubusercontent.com/assets/30694/7826487/c7728ad6-041a-11e5-870f-f341074dd3a7.png)

Also, if anyone is bothered the logos aren't equally sized I think the SVGs must be fixed to not have whitespace padding.

**Comment by MichelvanderAa** [comment]
What if we put them above the text on the 'About' page ?  
I think all logos should have the same height and spacing in between. And together they should for a row as wide as the text column. 
You can leave out the Truth.io icon, so only place: HF, Sydney, Google and The Space  (4 icons)

**Comment by Yolijn** [comment]
![screen shot 2015-05-28 at 16 25 10](https://cloud.githubusercontent.com/assets/877246/7862464/5d053c56-0556-11e5-8cf5-8529ad69a75d.png)

Please crop the SVGs so that all padding is removed. Logo's should touch at the edges of the image.

**Comment by Grrr-Josephine** [comment]
I emailed it. Let me know if it's working out.

**Comment by MichelvanderAa** [comment]
Sorry Yolijn, we have to remove the Truth.io logo again. So please spread the 4 remaining logos!

**Comment by Yolijn** [comment]
Done, removed Truth.io and spread remaining logos evenly. Also fixed the scrolling bug that was caused by adding of the logos the first time.
![screen shot 2015-05-28 at 22 01 38](https://cloud.githubusercontent.com/assets/877246/7869763/2d4c133e-0585-11e5-918f-a9912719c808.png)
