### ISSUE TITLE
HD switching doesn't work

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#21]
When pressing the HD icon the quality doesn't change, it keeps playing in 720p, not 1080p
![screen shot 2015-05-27 at 10 36 28](https://cloud.githubusercontent.com/assets/12616308/7832066/680ce2e8-045c-11e5-8ea8-31846002c8d1.png)

**Comment by robbert** [comment]
The URL says `vq=hd1080` -- on YouTube that setting doesn't have any effect, but it indicates that `hd1080` quality was the active setting. It might be that the `hd1080` wasn't buffered yet.

**Comment by MichelvanderAa** [comment]
Even if I let it run for 2 minutes the quality doesn't go up to 1080p. It should have buffered by then...
![screen shot 2015-05-27 at 11 15 09](https://cloud.githubusercontent.com/assets/12616308/7832764/cce52022-0461-11e5-8398-e423c32e6eeb.png)

**Comment by robbert** [comment]
I see. To prevent uncertainty about this in the future, I've fixed the URL: now when you press `V` it will link to the effective playback quality, not the desired playback quality.

Still need to investigate this further.

**Comment by robbert** [comment]
Hmm... there still is a delay between the URL value and the actual rendered video. YouTube notifies us of the quality switch before it is actually visible. It is more accurate than before though, and I don't think there is any way to improve this because we cannot detect when YouTube isn't telling the truth.

**Comment by robbert** [comment]
I'm still working on the HD button, but as a reminder here are the video quality links from the wiki:


[`?vq=large`](http://beta.bookofsand.nl/?vq=large) -- currently hosted by Vimeo

![screen shot 2015-05-27 at 22 45 16](https://cloud.githubusercontent.com/assets/30694/7847251/9be47232-04c2-11e5-99a2-0aa7620ffdf9.png)

[`?vq=hd720`](http://beta.bookofsand.nl/?vq=hd720) -- currently hosted by Vimeo

![screen shot 2015-05-27 at 22 45 30](https://cloud.githubusercontent.com/assets/30694/7847280/bdf12d84-04c2-11e5-8a4f-eb938406fb75.png)

[`?vq=hd1080`](http://beta.bookofsand.nl/?vq=hd1080) -- currently hosted by Vimeo

![screen shot 2015-05-27 at 22 45 45](https://cloud.githubusercontent.com/assets/30694/7847270/aacad49e-04c2-11e5-9b8f-a963d72509db.png)

[`?vq=highres`](http://beta.bookofsand.nl/?vq=highres) -- master version on Amazon S3

![screen shot 2015-05-27 at 22 46 23](https://cloud.githubusercontent.com/assets/30694/7847273/ae342db0-04c2-11e5-8fc6-b9f884ae076e.png)

**Comment by MichelvanderAa** [comment]
Robbert, lets select the Vimeo "?vq=hd720" as start-up SD resolution for now, and for HD choose the "?vq=highres" version on S3

**Comment by robbert** [comment]
I've updated the default quality to `hd720`. (Was `hd1080`.)

**Comment by MichelvanderAa** [comment]
Please fix/bring back the grey icon background when HD is selected. 

Is the HD option clear enough like this or should we introduce HD letters in the left top corner like Vimeo?
