### ISSUE TITLE
Fix layout loading screen

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#22]
1) Please make the smaller font slightly bigger (Kate Miller-Heidke etc)

2) Please make all text in the same colour red and/or have the same transparency (as used in Kate Miller-Heidke)

3) The text and logo isn't centered right vertically (there's more space on top than on bottom), this is why logo feels too low on the screen. Can you move everything up a bit.

**Comment by robbert** [comment]
Has been fixed this afternoon. Also, the background image in the splash screen is back.

**Comment by MichelvanderAa** [comment]
yihoe, thx
