### ISSUE TITLE
Cursor change in middle big circle

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#23]
The cursor changes into a hand while hovering in the middle of the big circle. This behaviour should only happen in the beginning when the play button is there. It's confusing that it still happens while playing, it indicates interaction that isn't there. Only on the circle lines the cursor should change to indicate the possibility for jumping in time.

**Comment by MichelvanderAa** [comment]
Now the cursor doesn't change to hand in the beginning anymore (when you hover over the play button)

**Comment by robbert** [comment]
Fixed.
