### ISSUE TITLE
Site werkt niet op IE 11 / Windows 7 pro SP1

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#24]
Windows 7 pro SP1
IE 11.0.9600.17691

"Duurt lang voordat er iets gebeurd, gaat dan spelen zonder geluid. En ik zie maar 1 laag en geen interface of mogelijkheid tot schakelen. Als ik dubbelklik voor fullscreen zie ik de video in 3 lagen."

**Comment by robbert** [comment]
Weird... works on my machine.

![screen shot 2015-05-27 at 12 40 43](https://cloud.githubusercontent.com/assets/30694/7834245/b031e896-046d-11e5-97de-92fa633b09bd.png)

**Comment by robbert** [comment]
I can reproduce audio issues now.

**Comment by MichelvanderAa** [comment]
Update: Jochem vertelt me net dat deze nieuwe Vimeo versie ook nog niet werkt op Win 7 pro SP1 en met nieuwste IE

**Comment by robbert** [comment]
The maximum video resolution on Windows 7 appears to be 1920×1088, for one reason or another. Maybe that has something to do with it. I'm converting test videos at 1088 height and 1088 width now.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd797815(v=vs.85).aspx

**Comment by robbert** [comment]
A blog post on the matter:

https://lars.st0ne.at/blog/html5+video+in+IE11+-+size+does+matter

**Comment by robbert** [comment]
Maximum video height in Internet Explorer is 1088 indeed.

Added video quality link to maximum Internet Explorer resolution:

[`?vq=iexplore`](http://beta.bookofsand.nl/?vq=iexplore) - 714×1088 video hosted on Amazon S3

The 4000×3000 or so logo video won't work either then.

**Comment by robbert** [comment]
Internet Explorer now always uses that 714×1088 video and the HD button is removed (in that browser only).

**Comment by MichelvanderAa** [comment]
user feeback:

"ihaa!! Perfect lip sync, en spoelen gaat ook soepeltjes!
Wel twee bugs: na een refresh deed in eerste instantie het geluid het ineens niet meer.
Na nog een refresh wel weer geluid, maar blijft de loading bar op 25% steken. Als ik dan ergens klik gaat hij wel afspelen. Na een tijdje gaat de loading bar verder naar 100% en verdwijnt dan alsnog.
 
Ook heb ik de indruk dat de interface-overlay niet snel of vaak genoeg verdwijnt. Soms blijft hij gewoon, of moet ik eerst de muis weg bewegen boven de knoppen. Ik zou hem gewoon altijd na een aantal seconden laten verdwijnen als er niet of alleen via keyboard wordt geïnteracteerd. Vermoed dat dat ook de bedoeling is maar werkt dus nog niet helemaal."

**Comment by MichelvanderAa** [comment]
Update van Jochem:
"Chrome draait prima (alleen SD dan, HD hapert)
IE: loading scherm doet het niet echt - geen animatie, geen loading bar. Als ik doorklik gaat hij wel spelen, overgang is rommelig, maar dan doet hij het op gegeven moment wel prima. 
Kan dus niet goed beoordelen in hoeverre dat allemaal aan mijn bandbreedte ligt, maar aangezien Chrome 'm wel perfect draait..."

**Comment by robbert** [comment]
Animatie tijdens heel veel audio tracks en video tracks laden is ook tricky natuurlijk, dat het hapert is te verwachten. In IE is dus geen logo video mogelijk totdat we de achtergrond met het eerste frame in de logo-video verwerken, zie opmerkingen eerder in deze bug. Als de rendering 'hangt' dan zal de progress bar ook niet doorlopen, ook al zou er voortgang zijn. Sommige browsers kunnen beter omgaan met dingen parallel uitrekenen dan andere.

Het klopt dat de voortgangsbalk in IE11 bij mij ook doorloopt in stappen van 25%, ik zal eens uitzoeken of IE tussendoor niet wat info geeft over de voortgang van het bufferen.

**Comment by MichelvanderAa** [comment]
Nog een update van Jochem:

"Nu thuis nog een keer op wifi geprobeerd.
Er gaat iets mis met bufferen. Probleem is dat als je klikt (ergens in het logo ofzo?), hij wel begint te spelen. Maar dan moet hij nog bufferen. Zodra hij is uitgebufferd, begint hij met jullie 'uitleg' van de interface, incl. een paar keer heen en weer schakelen, maar ik ben dan al aan het kijken. Dus die uitleg zou je alleen moeten laten komen als er geen interactie is vóór einde bufferen. Of alle mogelijkheden om toch te spelen als hij nog niet is uitgebufferd uitbannen. "

**Comment by robbert** [comment]
Click on logo now doesn't have an effect anymore, I had used that previously for debugging.

**Comment by MichelvanderAa** [comment]
But does that solve the problem of loading/buffering?

**Comment by robbert** [comment]
I guess not, but what I did do is move the audio files to Amazon S3, that might also help with the buffering.

In my windows virtual machine everything works snappy, so I'm asking around to borrow an actual slow Windows laptop right now.

**Comment by robbert** [comment]
Just tested on a 7-year old desktop PC with Windows 7, the loading on IE11 was snappy and playback worked well.

**Comment by MichelvanderAa** [comment]
I'm trying to find some more IE testers at the moment via Facebook and Twitter
http://www.facebook.com/michelvanderaa

**Comment by MichelvanderAa** [comment]
-> 
Even in het licht van onderstaande, en het feit dat IE altijd in sd-kwaliteit zal blijven werken (klopt het dat Chrome op Win7 wel in HD werkt?): hoe gaan we communiceren dat de site op IE niet optimaal te beleven is?
Een positieve formulering is het beste, iets als: ‘Deze site werkt optimaal in Chrome, Safari en mobiele browsers’ in een popupje voor IE-gebruikers? Of minder opdringerig?
Groet,
Jochem

**Comment by MichelvanderAa** [comment]
Update Jochem:
"Buffering gaat goed, balkje loopt mooi vol (wel langzaam hier)
Kan niet doorklikken als hij nog niet klaar is (das goed dus!)
Verder loopt alles goed bij afspelen. Spoelen gaat ok, schakelen ook, alles lipsync."

**Comment by robbert** [comment]
Closed then?

**Comment by MichelvanderAa** [comment]
yes looks like it! I have some more people testing. We'll reopen if necessary
