### ISSUE TITLE
Consider WebM / VP9 encoding for video

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#25]
Here's a plugin for Adobe software for this codec:
http://www.fnordware.com/WebM/

**Comment by robbert** [comment]
The screenshot you sent earlier wasn't actually 720p, it appears to be 360! The resolution is `462×720`.

![screen shot 2015-05-27 at 11 15 09](https://cloud.githubusercontent.com/assets/12616308/7832764/cce52022-0461-11e5-8398-e423c32e6eeb.png)

Check this out, this is the latest video when I set it to 360p -- the resolution is `462×720` too.

![screen shot 2015-05-27 at 14 55 06](https://cloud.githubusercontent.com/assets/30694/7836493/e5b95bda-0480-11e5-9619-96be36414892.png)


And this is the latest video on 720p, the resolution is different, it is `946×1440`.
![screen shot 2015-05-27 at 14 54 54](https://cloud.githubusercontent.com/assets/30694/7836498/eb728218-0480-11e5-9100-c011e3427f71.png)

The [older video](https://www.youtube.com/watch?v=-d1-XIFy-0c&hd=1) shows in "stats for nerds" that for the lower resolutions it does correctly play @25fps, and earlier we didn't have the YouTube sync problem.

**Comment by MichelvanderAa** [comment]
Think its a bit more complex. When I check frame-rates in Safari it shows what looks like more detailed stats. Both versions drop frames and both versions fluctuate between 24-27 fps. 

![screen shot 2015-05-27 at 15 31 04](https://cloud.githubusercontent.com/assets/12616308/7837169/d72bde9e-0485-11e5-8712-43b9947cbde0.png)
![screen shot 2015-05-27 at 15 31 18](https://cloud.githubusercontent.com/assets/12616308/7837170/d7310338-0485-11e5-96f1-fffaa97204f6.png)

Your 'Tryst Tryptich' is the render I made for you right?  Only difference is that that one is 10MBps and mine 15Mbps.  I will try upload a 10Mbps render of the graded video and see if that helps.
