### ISSUE TITLE
Remove clicking on circle line to jump

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#26]
Please remove clicking on circle line to jump. To many accidental jumps happen due to this feature. Dragging the small ball should be the only way to jump. Also, it's a linear story so I don't want invite jumping in time too much.

**Comment by MichelvanderAa** [comment]
Remove hand in middle circle

**Comment by Grrr-Josephine** [comment]
About dragging the small ball, it is not working if you drag it for less than half the circle. Did you notice? Are you on it?

**Comment by robbert** [comment]
Yes, we have been exploring multiple variations for dragging along the timeline. Some thing don't work well together:

* When clicking through the interface you really don't want to accidentally jump to another part of the video.
* The small circle is too small to grab hold of on touch devices, so ideally you are able to grab the whole circle. To prevent accidental touches I added a minimum drag duration of 650ms or so: if you let go before that the handle will move back and ignore the dragging.
* When you need to rewind only a couple of seconds the 650ms is unhelpful.

Etcetera.

**Comment by MichelvanderAa** [comment]
it's still not possible to jump back or forward a little bit, the ball bounces back...

**Comment by robbert** [comment]
Fixed.

The entire circle still has a `grab` mouse cursor, but it would require a major rewrite to fix that.

For really small adjustments in time there still is a 0.25s threshold to prevent accidental clicks.
