### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#3]

**Comment by Yolijn** [comment]
Done, beta.bookofsand and thebookofsand.net are tracked by Analytics account of Holland Festival Amsterdam

**Comment by MichelvanderAa** [comment]
Super, can you give me the inlog code as well so I can check as well?

**Comment by robbert** [comment]
We should add analytics to the Sydney Festival page and the browser-not-supported page as well.

**Comment by Yolijn** [comment]
Zijn de gegevens van Holland Festival google account, Robbert dacht dat jij die gegevens hebt?

Je kan dan bijvoorbeeld kijken op https://www.google.com/analytics/web/?hl=en#realtime/rt-overview/a63589238w99168431p103145329/ <https://www.google.com/analytics/web/?hl=en#realtime/rt-overview/a63589238w99168431p103145329/>

Groet!

**Comment by MichelvanderAa** [comment]
Ja dank, had ik gevonden, maar hij lijkt (nog) niets bij te houden ?

**Comment by Yolijn** [comment]
Fixed! Omdat we de beta bijhielden om te testen haalde de live analytics niets op. Nu doet hij het: als ik zelf de pagina open laat hij 1 live user zien.

**Comment by Yolijn** [comment]
![Uploading Screen Shot 2015-05-31 at 20.42.07.png…]()
![screen shot 2015-05-31 at 20 36 34](https://cloud.githubusercontent.com/assets/877246/7903235/cf13d704-07d5-11e5-8e4f-9fabc1941e37.png)

**Comment by MichelvanderAa** [comment]
dank!

**Comment by MichelvanderAa** [comment]
grrrr heel veel mobile users...hoop dat die terug komen
