### ISSUE TITLE
Stop/mute audio when switch to different quality SD/HD ?

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#30]
Would be good to mute the audio while switching format. On a slower connection you're watching a black screen for quite a time while buffering for HD and in the meantime the audio continues. Feels to the user that something goes wrong.

**Comment by MichelvanderAa** [comment]
Pauze audio & show spinner to indicate buffering

**Comment by robbert** [comment]
Fixed. For the spinner we have a separate issue: #54
