### ISSUE TITLE
Improve visibility SD / HD options in IU

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#33]
start with lighter grey HD icon? Then when chosen use grey background

add HD icon on top left corner of video like Vimeo ?

**Comment by robbert** [comment]
The new and improved HD icon:

![screen shot 2015-05-28 at 17 45 10](https://cloud.githubusercontent.com/assets/30694/7864265/5f41c588-0561-11e5-9b5b-f5f30201602b.png)

CLICK ME!!!1

**Comment by robbert** [comment]
This should make it clear HD is turned on.

![screen shot 2015-05-28 at 21 54 12](https://cloud.githubusercontent.com/assets/30694/7869610/26d41624-0584-11e5-94fd-d36ae42028a1.png)

**Comment by MichelvanderAa** [comment]
Glitch: when HD is selected en you press another icon (for example subtitle) the HD icon turns into a white square

**Comment by robbert** [comment]
@Yolijn The glitch could be fixed by not applying the CSS `transform: scale(..)` in HTML but in the SVG file itself, using `<g transform="scale(...)">`.

**Comment by Yolijn** [comment]
Fixed!
