### ISSUE TITLE
Firefox windows 7 werkt niet, blijft hangen op 75% loading screen

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#34]
(feedback via vertaler Hans Kloos)

**Comment by robbert** [comment]
Dit was ná de nieuwe Firefox?

**Comment by robbert** [comment]
Just tested Firefox on two Window 7 machines, worked fine.

**Comment by robbert** [comment]
I have just experienced this situation myself, and using the developer console I wrote some code to fix this -- and the video continued loading, and the splash screen disappeared correctly.

I have now added code to check if the video is stalled loading, and run the code that fixed the situation for me in that one time. This situation is not readily reproducible, so there is no other way to test this than wait for any new reports of this bug.
