### ISSUE TITLE
The introduction to the interaction is not really clear.

### ISSUE THREAD

**Issue by Grrr-Josephine** [robbert/book-of-sand#35]
Our main concern is about the introduction/presentation of the interaction.
The moving between layers demonstration is confusing.

- We would delete the auto moving between layers at the beginning. It is too much movements. It starts too early. It doesn't explain really well. It gives you the feeling it's complicated and also that you don't control anything.

- We would keep the sentence and the navigation displayed until you actually navigate for the first time between the layers. (To make sure people get it.)

- For a nice experience we would start the video immediately. And then delete the play button in the circle. This play button is also too big and as it's not reappearing when you pause the video, it's not consistent.

- We would make the explanation sentence looks like an explanation and not like a subtitle (otherwise when you scan the page you don't read.) For that we would: - put it in a box. - put a Capital at the beginning of the sentence and a dot at the end. - Put it more up, not at the place of a subtitle.

**Comment by MichelvanderAa** [comment]
Thanks, some good points. We have an idea to improve things. Stay tuned!

**Comment by robbert** [comment]
- Auto moving is still in, but I've increased the delay between switches from 1,5s to 3,3s.

- Tutorial text remains visible until someone switches layers. When you press play, the tutorial text remains visible. The controls remain visible until you switch layers.

- Hallway testing lead us to believe The Big Button is a Good Thing™.

- The Big Button is not reappearing. Maybe it should.

- Now there's a very unsubtle big box with a call to action.

![screen shot 2015-05-28 at 22 46 09](https://cloud.githubusercontent.com/assets/30694/7870725/5d90c494-058b-11e5-8f2a-749aa72065d1.png)

**Comment by MichelvanderAa** [comment]
I think the speed of the tilt is a tiny bit too slow now Robbert, perhaps change it to something in between what we started with and what we have now

**Comment by robbert** [comment]
A friend of mine tested the website, and he totally ignored the text box and just clicked play. Only three minutes into the video he bothered to read the text and clicked on one of the small circles.

**Comment by MichelvanderAa** [comment]
does he have a white walking stick with red stripes?  ;-)

**Comment by robbert** [comment]
No, dyslexia.
