### ISSUE TITLE
About page can be smoother.

### ISSUE THREAD

**Issue by Grrr-Josephine** [robbert/book-of-sand#36]
It is really last priority, really refinement,
but the transition to the about page is really dry/curt,
the experience would be better with a smoother transition.
- The audio could fade out / fade in
- The visual could move, or also fade.

(The about button on the home page could be smaller and with a bit more padding from the left.)

**Comment by Yolijn** [comment]
Added animation to show and hide the about pages.

Robbert, do you think we could/should fade the audio?

**Comment by MichelvanderAa** [comment]
audio fade isn't needed in my opinion
