### ISSUE TITLE
Credit addition

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#37]
Could you please add: 

Fonds Podiumkunsten

to the list of "with additional support by"
(under Nederlands Kamerkoor)

**Comment by Yolijn** [comment]
![screen shot 2015-05-28 at 22 08 17](https://cloud.githubusercontent.com/assets/877246/7869944/16ff3394-0586-11e5-8097-ec2f92646cf7.png)

**Comment by MichelvanderAa** [comment]
Die afbreking bij 'Lyon' is me een beetje een doorn in het oog, misschien kan je het zo doen:

Grame /
Biennale Musiques Scène Lyon
Nederlands Kamerkoor
Fonds Podiumkunsten

**Comment by Yolijn** [comment]
![screen shot 2015-05-28 at 22 45 23](https://cloud.githubusercontent.com/assets/877246/7870693/453ce850-058b-11e5-9938-010822ef3d8f.png)

**Comment by MichelvanderAa** [comment]
yes √

**Comment by Yolijn** [comment]
Ik zie in eerdere mailtjes dat hier ook TRUTH.io bij stond, maar kan het hier niet vinden. Moeten zij toegevoegd worden aan de credits onder additional support en zo ja op welke hoogte?

**Comment by MichelvanderAa** [comment]
Dat is nog even 'on hold', het HF beslist, maar ik verwacht dat ze er toch niet bij mogen

**Comment by MichelvanderAa** [comment]
Ok some changes that the HF wants to make:

We need to add this logo to our logo row:
http://fondspodiumkunsten.nl/nl/over_het_fonds/logo/
Can you make this work or does Josephine need to turn it into a .svg ?

The HF wants us to move the logos to the credit page in between the artistic team and the commissioners (see below)

And we need to change the credit text as follows:
---

composition, film script, direction		Michel van der Aa
based on short stories by			Jorge Luis Borges
mezzo-soprano					Kate Miller-Heidke
**choir**						        Nederlands Kamerkoor
conductor					                 MaNOj Kamps
 
co-commissioned and coproduced by	Holland Festival
						                Sydney Festival
						                Google Cultural Institute
developed in association with			BBC The Space
with additional support by			Grame /
						                Biennale Musiques en Scène Lyon
						                Nederlands Kamerkoor
**musical composition with support by	Performing Arts Fund NL**

**LOGOS (5 stuks)**

website & app development			Robbert Broersma
ETC

**Comment by Yolijn** [comment]
Done!
![screen shot 2015-05-29 at 17 06 57](https://cloud.githubusercontent.com/assets/877246/7885618/322a060e-0625-11e5-8d74-3e5da1ad34a7.png)
![screen shot 2015-05-29 at 17 06 46](https://cloud.githubusercontent.com/assets/877246/7885617/3225e61e-0625-11e5-9984-d3370f784037.png)

**Comment by MichelvanderAa** [comment]
great lets put this online so HF can check, thx
