### ISSUE TITLE
Change start-up navigation text and position

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#39]
Yolijn,
Could you please change the navigation text to this (correct English):

To choose a film layer 
click on these circles, 
or use the arrow up and down keys 
on your keyboard.

Also it might be good to have the text box closer to the navigator so that it's more clearly linked.

**Comment by Yolijn** [comment]
Done! ![screen shot 2015-05-28 at 22 31 29](https://cloud.githubusercontent.com/assets/877246/7870511/119b3c64-058a-11e5-94a8-fba6d3eaff9d.png)

**Comment by Yolijn** [comment]
We need another tutorial text for the mobile version, something with swipe instead of arrow keys.

**Comment by MichelvanderAa** [comment]
Josephine, hows this ?  Quite a brute layout but perhaps its more important the user won't miss it?
