### ISSUE TITLE
Show message to install app on iOS devices

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#4]

**Comment by MichelvanderAa** [comment]
This becomes more urgent now that a larger group is beta testing. I already received a few messages that the site doesn't work on iPad/iPhone

**Comment by robbert** [comment]
Working on it.

**Comment by robbert** [comment]
I'm going to use the official iTunes store download badge I've found here:

https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore

**Comment by MichelvanderAa** [comment]
Ok , as long as it also contains a text such as:
This website is not supported on your  device. You can download our official App from the Appstore.

**Comment by robbert** [comment]
I have added the iOS detection script and a basic message to the iPad splash screen.

![img_0300](https://cloud.githubusercontent.com/assets/30694/7884171/40ed6b26-061c-11e5-886b-2b55c0abc8b0.PNG)
![img_0301](https://cloud.githubusercontent.com/assets/30694/7884172/41235a56-061c-11e5-981a-ac94140e9403.PNG)

@Yolijn can add a button to the iPhone splash screen and do further tweaking.

**Comment by robbert** [comment]
By the way, I don't think it is necessarily needed to say something negative about the browsers capabilities, the App Store icon is good enough I think, many websites work like this.

**Comment by MichelvanderAa** [comment]
ok

Lets make the lower text:

This App will be available in the App Store soon!

(more positive). And maybe remove the dot after 'stay stuned' ?

**Comment by robbert** [comment]
What Apple has to say on the matter:

![screen shot 2015-05-29 at 16 08 18](https://cloud.githubusercontent.com/assets/30694/7884305/09c26e48-061d-11e5-9937-e6e1bdc79419.png)

**Comment by MichelvanderAa** [comment]
Lets make the lower text:

This App will be available in the App Store soon!

(more positive). And maybe remove the dot after 'stay stuned' ?

**Comment by robbert** [comment]
Fixed.
