### ISSUE TITLE
Preload HD video when switching to HD before playing

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#40]
Currently only the initial video is preloaded, when pressing play after switching to HD the screen goes black while the video loads.

![screen shot 2015-05-28 at 20 32 02](https://cloud.githubusercontent.com/assets/30694/7867846/a5d85108-0578-11e5-8834-cfcfcb42e628.png)

**Comment by MichelvanderAa** [comment]
I think it would be good for the audio to pauze/mute as well while new video loads

**Comment by robbert** [comment]
Fixed. The muting/pausing will be handled in issue #30, but it doesn't apply to this issue specifically as this issue is about switching when the video paused already.
