### ISSUE TITLE
Subtitles; change "numbers" to Italic?

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#42]
Yolijn,

Is it possible to change the font in the subtitles for the nine numbers to Italic ?

->
Three, five, nine, twelve.
Six, fourteen, seventeen, eighteen, nineteen.

**Comment by robbert** [comment]
Nope, the subtitle library doesn't support markup. We discussed this already two months ago at Grrr HQ.

**Comment by MichelvanderAa** [comment]
ok just checking
