### ISSUE TITLE
positioning of text/logo loading screen

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#43]
It all feels still a tiny bit too low, can you move everything a few pixels up?

**Comment by MichelvanderAa** [comment]
Oh en misschien dan ook meteen de regelafstand tussen Kate Miller-Heidke en Nederlands Kamerkoor gelijk maken aan regelafstand van linker kolom

**Comment by Yolijn** [comment]
![screen shot 2015-05-28 at 23 56 34](https://cloud.githubusercontent.com/assets/877246/7872117/b00b0d92-0595-11e5-82dd-a68b6adac607.png)
