### ISSUE TITLE
Quality start-up still/photo

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#44]
the start up still/photo suddenly looks quite bad (lower res and darker). Is there a reason/need for this?

**Comment by robbert** [comment]
Better like this?

**Comment by robbert** [comment]
I mean: 
![screen shot 2015-05-29 at 10 49 18](https://cloud.githubusercontent.com/assets/30694/7879396/602463e0-05f0-11e5-816a-3a558e19abd0.png)

**Comment by MichelvanderAa** [comment]
I can't really judge need to see the tilt after the loading screen. Colour now seems washed out and slightly to dark. You want me to make a new one?  You need a jpg right?

**Comment by MichelvanderAa** [comment]
so I'm talking about the background photo, not the text or logo

**Comment by robbert** [comment]
Yes, you can upload a new `.jpg` and the effect will be visible immediately. If you change the poster image, it's best to upload the `.jpg` and `.png` together so we always have the uncompressed original at hand.

**Comment by MichelvanderAa** [comment]
ok I've changed the photo
