### ISSUE TITLE
Facebook embed text

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#46]
When I now share the beta site link on Facebook it lists the following text:

![screen shot 2015-05-29 at 12 09 34](https://cloud.githubusercontent.com/assets/12616308/7880640/c2440c46-05fb-11e5-9d2d-7aa71ec2b4c5.png)

Do we have control over this? If so please add the first paragraph of the 'about' text.

**Comment by robbert** [comment]
@Yolijn Maybe this can be fixed using Facebook Open Graph meta tags.

First hit on Google is a blog post by David Walsh (remember him?)

http://davidwalsh.name/facebook-meta-tags

**Comment by MichelvanderAa** [comment]
Can we make it embed a photo as well?

**Comment by Yolijn** [comment]
Yes it seems so, want to use te logo, or do you have another image in mind?

**Comment by MichelvanderAa** [comment]
I'll provide an image. Does it have to be square? What resolution?

**Comment by Yolijn** [comment]
This is what Facebook has to say about it:
https://developers.facebook.com/docs/sharing/best-practices#images <https://developers.facebook.com/docs/sharing/best-practices#images>

So it doesn’t have to be square and it all depends on the image size you want in your share.
The minimum image size is 200x200px.

Could you also run the image trough the URL Debugger <https://developers.facebook.com/tools/debug>, I don’t have a Facebook account :-)

**Comment by MichelvanderAa** [comment]
ok here's one:

![thebookofsand_still_katemillerheidke](https://cloud.githubusercontent.com/assets/12616308/7886409/3bcda9d6-062a-11e5-8015-7297dfea2117.jpg)

I have no idea how to run an image through that debug page...

**Comment by Yolijn** [comment]
![screen shot 2015-05-29 at 19 01 01](https://cloud.githubusercontent.com/assets/877246/7887963/43e45c9a-0635-11e5-8bf4-8b74853b79b9.png)
done!

**Comment by MichelvanderAa** [comment]
great!
