### ISSUE TITLE
Audio type/specs S3 files not working on Firefox

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#47]
https://s3-eu-west-1.amazonaws.com/betaofsand/audio-2015-05-28/1.m4a

"Als ik de website op FireFox bekijk (FF 21.0 op OSX 10 Yosemite) komt de site niet verder dan het introductie-scherm. De console geeft aan: "Specified "type" attribute of "audio/mp4" is not supported."

**Comment by robbert** [comment]
Probably duplicate of #32, for old Firefox versions Ogg is required.
