### ISSUE TITLE
Add IP / Regionblock for Australia

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#49]

**Comment by robbert** [comment]
What should the website look like down under?

**Comment by MichelvanderAa** [comment]
We've emailed the Sydney Festival about this.

Until we hear from them maybe just leave the page black with the following text:

Sorry! This website is not yet available in your country.

**Comment by MichelvanderAa** [comment]
Festival director suggested this text:
"The Book of Sand will be launched in Australia and New Zealand on Thursday October 22 on the occasion of the 40th Sydney Festival program announcement."

**Comment by robbert** [comment]
I would rather redirect to a page on the Sydney Festival website, much like http://thebookofsand.net/ works now for Holland Festival.

**Comment by robbert** [comment]
For example: http://www.sydneyfestival.org.au/info/events

**Comment by MichelvanderAa** [comment]
ok I'll suggest this to them. But for the time being please use the text mentioned above. Because they won't get back to use before tomorrow

**Comment by robbert** [comment]
@Yolijn Could you make a page similar to `app.html` for this? Then I'll redirect to that.

**Comment by Yolijn** [comment]
![screen shot 2015-05-30 at 19 45 02](https://cloud.githubusercontent.com/assets/877246/7898573/6849a872-0704-11e5-831d-ff6043f2dd3c.png)
Done! Robbert can you create the redirect?

**Comment by MichelvanderAa** [comment]
Kan de onderste regel in een groter font en iets minder brede regel en hoger op de pagina

**Comment by robbert** [comment]
I have added the IP block to the temporary page on http://thebookofsand.net/ to be able to test this, and it appears to be working great:

![screen shot 2015-05-31 at 04 37 33](https://cloud.githubusercontent.com/assets/30694/7900317/278b7f86-074f-11e5-907d-b0a09fa8c6f9.png)

**Comment by MichelvanderAa** [comment]
super, but they say they need to make a landing page first. Can you until then just put the following text on our own site:
"The Book of Sand will be launched in Australia and New Zealand on Thursday October 22 on the occasion of the 40th Sydney Festival program announcement."

**Comment by robbert** [comment]
![screen shot 2015-05-31 at 13 05 54](https://cloud.githubusercontent.com/assets/30694/7901705/d8bd8704-0795-11e5-8ac3-a0f35b0ba028.png)

**Comment by MichelvanderAa** [comment]
Sydney Festival made a official landing page, here is the link to the redirect:

http://www.sydneyfestival.org.au/info/the-book-of-sand

**Comment by robbert** [comment]
Fixed.
