### ISSUE TITLE
Add play button in center of large circle when paused

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#5]

**Comment by robbert** [comment]
![screen shot 2015-05-27 at 04 52 16](https://cloud.githubusercontent.com/assets/30694/7827859/6cd2f040-042c-11e5-8dd6-ba14c7b1d300.png)

**Comment by MichelvanderAa** [comment]
You can still accidentally click on the circle line and jump forward instead of starting to play from 0:00. 
I feel the jumping feature should be disabled in this state.
