### ISSUE TITLE
Only accept 'play' after intro-tilt

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#50]
Can we delay the possibility to press 'play' until after the tilt has finished on the middle picture?  

Otherwise it's rather confusing to hear the music and see the video switch automatically ;-)

**Comment by robbert** [comment]
![screen shot 2015-05-30 at 00 03 35](https://cloud.githubusercontent.com/assets/30694/7893547/5a936ba0-065f-11e5-9166-99917a83c48e.png)

**Comment by Yolijn** [comment]
Done!
