### ISSUE TITLE
Firefox sometimes hangs on loading (75%)

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#51]
User report:

Systeem 1
Processor:   i7-3770 3.4GHz (quadcore)
OS:              Windows 8.1 64 bit
Geheugen:  8 Gb
Netwerk:     120 Mb

Firefox
- bleef lang hangen op 75% laden in standard
- stottert na het aanklikken van HD tot 80% laden. Dit duurde anderhalve minuut
- korte stotter op 5:32 bij "Six, Fourteen, Seventeen". Vanaf dat moment wordt er weer druk van de netwerkverbinding gebruik gemaakt voor buffering)
- daarna probleemloos

Systeem 2
Processor:   E8400 3.0GHz (dualcore)
OS:              Ubuntu 14.04TLS 64 bit
Geheugen:  4 Gb
Netwerk:     120 Mb

Firefox
- CPU gebruik stijgt naar 100% op twee cores. HD is daardoor niet af te spelen zonder te stotteren.
- Standaard gaat goed, maar belast de twee processoren toch nog 95%

Chrome
- Standaard gaat probleemloos
- Na het switchen naar HD loopt audio en video uit fase. Dit is alleen op te lossen door de site te refreshen. Als de hele site in HD is gebufferd, dan is het afspelen weer probleemloos.

**Comment by MichelvanderAa** [comment]
I can underline this problem. Sometimes Firefox hangs on 75% here as well.

So now we have three separate reports of this problem (incl Hans Kloos)

**Comment by robbert** [comment]
I'm going to investigate this further now, but it's going to take some time because it is hard to reproduce for me.

**Comment by robbert** [comment]
I just ran into the same issue on Safari, and it appeared to be the case that not only video sometimes stalls, but also audio. I've extended the script to retry loading all tracks when they hang.

Please reopen when reports of this issue resurface.

By the way, the beta now redirects to `/latest/` -- should makes no difference, but it saved us time to do it likes this.

**Comment by MichelvanderAa** [comment]
sorry, still hangs here at 75% ...

**Comment by robbert** [comment]
I'm going to build an URL parameter that automatically reloads the page until the splash screen hangs.

That should help.

**Comment by robbert** [comment]
[`?autorefresh`](http://beta.bookofsand.nl/?autorefresh) - refresh the page after the site has been loaded

**Comment by robbert** [comment]
Added four more CDN domain names, now different network sockets will be used to download the tracks, downloading only one file per connection should help prevent network sockets to hang.

`cdn.bookofsand.nl` - SD video
`cdn1.bookofsand.nl` - audio 1
`cdn2.bookofsand.nl` - audio 2
`cdn3.bookofsand.nl` - audio 3
`cdn4.bookofsand.nl` - HD video

![screen shot 2015-05-30 at 16 17 41](https://cloud.githubusercontent.com/assets/30694/7897760/a899d4f4-06e8-11e5-8104-d62b83fd6f58.png)
