### ISSUE TITLE
Create spinner to show while loading/buffering

### ISSUE THREAD

**Issue by Yolijn** [robbert/book-of-sand#54]
We need a spinner to show the user the website is still working and they just need to wait a bit for the content to be loaded.

**Comment by Yolijn** [comment]
Created loader gif, need to add .buffering class to div with id "loader".

**Comment by Yolijn** [comment]
Done, added loader. Needs testing to make sure it's shown when needed.
Reopen if issues are found :) 

![screen shot 2015-05-30 at 22 56 26](https://cloud.githubusercontent.com/assets/877246/7899344/d11f88ce-071f-11e5-9dd9-ce0e50e3c1aa.png)

**Comment by MichelvanderAa** [comment]
looks nice!  Small detail, it's not centered exactly in the middle of the navigator circle

i 'll also do some testing

**Comment by Yolijn** [comment]
All better now!

![screen shot 2015-05-30 at 23 52 35](https://cloud.githubusercontent.com/assets/877246/7899563/1800ccdc-0728-11e5-89d9-109a4282ad4f.png)
