### ISSUE TITLE
Firefox doesn't play new HD video

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#56]

**Comment by robbert** [comment]
![screen shot 2015-05-29 at 22 22 26](https://cloud.githubusercontent.com/assets/30694/7891983/4d9b2ca2-0651-11e5-9ad5-f7f5dc0d2539.png)

@MichelvanderAa You forgot to set the `video/mp4` content type.

**Comment by robbert** [comment]
NO YOU DIDNT JUST KIDDING.

**Comment by MichelvanderAa** [comment]
;-)
