### ISSUE TITLE
Use content delivery network to speed up loading in the USA

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#57]

**Comment by robbert** [comment]
Is this fast enough for you?

[`http://cdn.bookofsand.nl/MASTER+1280x1950_GRADED_25mei_15Mbps.mp4`](http://cdn.bookofsand.nl/MASTER+1280x1950_GRADED_25mei_15Mbps.mp4)

**Comment by robbert** [comment]
@MichelvanderAa 

Please have a look at the pricing before we launch. A read a blog somewhere saying the price of using CloudFront is roughly 50% than using S3 alone. Really cheap * 1.5 = still cheap, I figure.

http://aws.amazon.com/cloudfront/pricing/

**Comment by MichelvanderAa** [comment]
yes, lets do it, but not place 52 mirrors but one on each continent

**Comment by MichelvanderAa** [comment]
"Is this fast enough for you?
http://cdn.bookofsand.nl/MASTER+1280x1950_GRADED_25mei_15Mbps.mp4"

yes works fine here!

**Comment by MichelvanderAa** [comment]
I spoke with Sigi this morning and told her to keep an eye on the S3 costs. So lets place a few mirrors on strategic places.   (North-American, South America, Asia/Japan, East Europe/Russia)

**Comment by robbert** [comment]
I'm not an expert, but ballpark figures. Price per GB of traffic differs per region, varying from 9ct to 15ct per gigabyte, but most regions are 9ct. Watching the HD version takes roughly 1GB.

3,000 visitors * € 0,09 = € 270
75,000 visitors * € 0,09 = € 6750

We could disable the HD version when costs get out of hand. Current Amazon bill is circa € 15.

**Comment by MichelvanderAa** [comment]
But not everyone uses HD right?  How much is it for SD playback per visitor?
