### ISSUE TITLE
User interface tweaks for small iPhone screen with touch interface

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#58]
I have created this little testing page, to simulate the user interface on the iPad.

http://beta.bookofsand.nl/latest/iphone.html

![screen shot 2015-05-30 at 03 10 26](https://cloud.githubusercontent.com/assets/30694/7895027/74d4992a-0679-11e5-8652-df1742438807.png)

There are a couple of apparent UI issues we need to fix, and also we need to adjust the tutorial text to match touch interaction and no keyboard.

Also, the 5 second splash screen delay isn't enough to show every slide of the splash screen.

**Comment by MichelvanderAa** [comment]
can you send that bypass link to test the full site on iOS ? (without the audio switching)

Or is this it?

**Comment by robbert** [comment]
Current idea to replace tutorial text on small screens:

![img_1260](https://cloud.githubusercontent.com/assets/30694/7897955/b53fee48-06f0-11e5-8734-3f84b6d46655.JPG)

**Comment by robbert** [comment]
Please open separate issues when anything comes up.

**Comment by Yolijn** [comment]
All issues mentioned are fixed, if anything new comes up, please open separate issue
