### ISSUE TITLE
App: HD button (on) doesn't line up properly

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#61]

**Comment by robbert** [comment]
There shouldn't be an HD button in the app.

**Comment by MichelvanderAa** [comment]
there is on your mobile test page ;-)

http://beta.bookofsand.nl/latest/iphone.html

**Comment by robbert** [comment]
Oops.

**Comment by Yolijn** [comment]
![screen shot 2015-05-30 at 18 58 35](https://cloud.githubusercontent.com/assets/877246/7898363/ea1d9086-06fd-11e5-8474-52b22c222d29.png)
Fixed
