### ISSUE TITLE
Deploy app to testers remotely

### ISSUE THREAD

**Issue by Yolijn** [robbert/book-of-sand#63]
https://developer.apple.com/testflight/

**Comment by MichelvanderAa** [comment]
good idea!

**Comment by Yolijn** [comment]
After a lot of setup, Apple tells us they are approving the BETA and it can take up to 30 days... so sadly remote deployment via e-mail is not the way to go.

To approve devices for installing the beta app via Itunes we need the unique ID of each iOS device.
Michel could you supply me with the UDID of the devices you want to test?
http://whatsmyudid.com

With those I can create a file to install on those devices via Itunes.

**Comment by Yolijn** [comment]
## To install the app on a device
1. Connect the testing device to a Mac running iTunes.
If possible, don’t use a Mac that you use for development.
2. Double-click the iOS App file that you created earlier (the file with the *.ipa* extension).
3. In iTunes, click the device in the upper-left corner of the window.
4. Click the Apps button.
The app appears in the iTunes Apps list. 
![5_ios_installapp_1_2x](https://cloud.githubusercontent.com/assets/877246/7897349/38cc3568-06d9-11e5-90bf-223ff981f028.png)
5. Under Apps, choose “Sort by Name” or “Sort by Kind” from the pop-up menu.
An Install or Remove button appears adjacent to the app.
6. If an Install button appears, click it.
The button text changes to Will Install.
7. Click the Apply button or the Sync button in the lower-right corner to sync the device.
The app is uploaded to the device so that the user can start testing.

**Comment by MichelvanderAa** [comment]
UDID

iPhone:
dac394757229c8cbabbab939ff714872dc6c2e6f

iPad:
58b8b02062dee2b974aa85fe9d490e6d8645bfd9

**Comment by robbert** [comment]
There you go:

[Book of Sand 0.0.2](http://beta.bookofsand.nl/app/0.0.2.ipa)

**Comment by MichelvanderAa** [comment]
it installs on my iPhone but not on my iPad

on my iPad the 'install' button is greyed out...

**Comment by robbert** [comment]
[Book of Sand 0.0.3](http://beta.bookofsand.nl/app/0.0.3.ipa)

**Comment by MichelvanderAa** [comment]
iPad ID nog een keer gecopieerd, volgens mij hetzelfde als hier boven
58b8b02062dee2b974aa85fe9d490e6d8645bfd9

**Comment by MichelvanderAa** [comment]
Is er geen aparte link voor de iPad versie?

**Comment by Yolijn** [comment]
How about this one?
*Please remove all old apps from iTunes before opening this one, to prevent clashes and mixups*
Works on all our devices, checked the ID in the license key everything seems to be in place... 
http://beta.bookofsand.nl/app/0.0.3.2.ipa

**Comment by MichelvanderAa** [comment]
ok tried this, no luck, install button remains greyed out

**Comment by Yolijn** [comment]
Then I have nu clue what’s up… tried to find a solution with google but cannot find anybody who’s experiencing same problem (were some devices are ok with UDID and one device isn’t) The id is added to the Book of Sand devices by Apple, and the interface doesn’t allow me to remove and re-add the key.
Don’t think we can fix this unfortunately.

**Comment by MichelvanderAa** [comment]
ok then please send me some iPad screenshots to judge the video quality, thx

**Comment by robbert** [comment]
Screenshot request will be handled in #70, this one can be closed for now.
