### ISSUE TITLE
App: loading screen/credits

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#64]
Borges and the commissioners are now missing on the loading screens. 

How would it look like if we used the same loading screen as the website, with logo (not moving) and with the same text but one step larger font. Would that be readable?  We could leave this still for 4-5 seconds.

Can you try Yolijn?

**Comment by robbert** [comment]
We had it like that before, but the text was unintelligible at that size. The current mobile splash screen looks gorgeous. We should simply increase the duration of the loading screen.

**Comment by MichelvanderAa** [comment]
Ok but then we have to add a third page that mentions Borges and the Commissioners (leave out Google please)

**Comment by robbert** [comment]
The third page was there all along, the splash screen would simply disappear before it got there.

Fixed now: the splash screen shows 7.5s minimum on mobile screens.

![screen shot 2015-05-30 at 16 45 19](https://cloud.githubusercontent.com/assets/30694/7897814/61c17ade-06eb-11e5-9a86-0d1051da9074.png)
