### ISSUE TITLE
iOS app requires demo screenshots

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#66]

**Comment by MichelvanderAa** [comment]
Ik heb de app nog niet dus kan geen screenshots maken.  Hier is een voorstel voor drie punten:

2:33 bovenlaag
referentie:
![screen shot 2015-05-30 at 14 49 49](https://cloud.githubusercontent.com/assets/12616308/7897410/a6b708d0-06db-11e5-93ff-ae187d9eb945.png)

5:21 middenlaag
referentie:
![screen shot 2015-05-30 at 14 49 16](https://cloud.githubusercontent.com/assets/12616308/7897411/ae2ce49a-06db-11e5-8a4f-92f38ccfd050.png)

2:30 onderlaag
referentie:
![screen shot 2015-05-30 at 14 53 05](https://cloud.githubusercontent.com/assets/12616308/7897413/b576fbb4-06db-11e5-8fc1-ec1926b1745f.png)

---
demo video is niet verplicht toch? zie ik bijna nergens bij staan

**Comment by MichelvanderAa** [comment]
ik kan met de app wel een paar screenshots maken maar dan moet die audio-delay viewer code er even uit..

**Comment by MichelvanderAa** [comment]
Hoi Yolijn, 
Hier zijn de screenshots voor de Appstore:
http://www.dropbox.com/s/pvb6p9rl9gmjo9r/iOS%20screenshots.zip?dl=0

Ik heb er 8 gemaakt, graag op deze volgorde laten verschijnen in die screenshot gallery!
gr Michel

**Comment by Yolijn** [comment]
De huidige screenshots hebben niet het goede formaat. We kunnen 5 screenshots per aangegeven device formaat insturen. Minimaal 1 per formaat.

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2

**Comment by robbert** [comment]
Heb het tooltje uitgebreid met de officiële screenshot resoluties:

http://beta.bookofsand.nl/iphone.html

Je had een retina MacBook Pro toch? Dan kun je het best daarmee de screenshots maken.

**Comment by MichelvanderAa** [comment]
√
