### ISSUE TITLE
iOS app requires copyright to be stated

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#68]
What's the copyright line?

**Comment by MichelvanderAa** [comment]
Developer: Holland Festival, Sydney Festival Ltd.

Copyright: © 2015 Michel van der Aa. Excerpts from "La casa de Asterion", "El aleph", "El zahir", and "La biblioteca de Babel" by Jorge Luis Borges. Copyright © 1995 by Maria Kodama, used by permission of The Wylie Agency LLC

**Comment by robbert** [comment]
"lie Agency LLC" doesn't fit, the copyright text should be slightly shorter than the proposed text.

**Comment by MichelvanderAa** [comment]
hang on

**Comment by robbert** [comment]
This fits:

`© 2015 Michel van der Aa. Excerpts from "La casa de Asterion", "El aleph", "El zahir", and "La biblioteca de Babel" by Jorge Luis Borges. © 1995 by Maria Kodama, used by permission of The Wylie Agency LLC`

I removed the two instances of `Copyright`.

**Comment by robbert** [comment]
And I don't see anything here to add the Developer info.

**Comment by MichelvanderAa** [comment]
they've changed their mind, want to make it simpler:

© 2015 Holland Festival and Sydney Festival Ltd.
