### ISSUE TITLE
The FINAL credit change...

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#69]
Ok .. HF received final word on credits and logos.....

1 - On the loading screen 'Google' needs to be removed. Only Holland Festival and Sydney Festival should be listed

===============
2 - On the credit page the logos have to move up, under "conductor MaNOj Kamps" and above 
"co-commissioned and coproduced by Holland Festival"

===============
3 - The Sydney Festival logo needs to be second, so needs to swap place with Google.  
Order : HF, SF, Google, The Space, Fonds Podiumkunsten
(looks worse...i know...)
*UPDATE: never mind, if it looks better they say leave it like this*

===============
4- The commission credits need to be changed to:

![screen shot 2015-05-30 at 15 28 49](https://cloud.githubusercontent.com/assets/12616308/7897568/9a01ce2c-06e0-11e5-856d-30ba4394b0ad.png)

---
Kan je Grame-Lyon op 1 regel krijgen?

===============
5 - On 'about':
Composed in partnership with the Holland Festival, Sydney Festival, Google Cultural Institute, and BBC’s The Space, and created exclusively in digital format, The Book of Sand was launched on 31st May as a website and smartphone app .

should change into:

Created in partnership with the Holland Festival, Sydney Festival, Google Cultural Institute, BBC The Space and other partners, and created exclusively in digital format, The Book of Sand was launched on 31st May as a website and smartphone app.
===============

thx

**Comment by MichelvanderAa** [comment]
De icons moet alleen nog naar boven, zie punt 2

**Comment by MichelvanderAa** [comment]
oh en het is een beetje lelijk dat er nu twee kolom breedtes zijn. Als dat de consequentie is van Grame-lyon op 1 regel, spilts die dan maar weer over 2 regels

**Comment by robbert** [comment]
All fixed now.
