### ISSUE TITLE
App: create HD app for iPad with higher res video?

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#70]
I'll check first and see how good/back the current low-res version looks on my iPad...

**Comment by robbert** [comment]
[`http://beta.bookofsand.nl/?vq=iphone`](http://beta.bookofsand.nl/?vq=iphone)

**Comment by robbert** [comment]
![screen shot 2015-05-31 at 00 33 14](https://cloud.githubusercontent.com/assets/30694/7899664/172f0260-072d-11e5-89b0-41d5ef3a4322.png)

![screen shot 2015-05-31 at 00 33 40](https://cloud.githubusercontent.com/assets/30694/7899663/172db266-072d-11e5-9a11-34724a9cc96b.png)

![screen shot 2015-05-31 at 00 34 11](https://cloud.githubusercontent.com/assets/30694/7899662/172b74ce-072d-11e5-8c35-a03ca6f98d30.png)

Ter referentie, dit is HD:

![screen shot 2015-05-31 at 00 35 44](https://cloud.githubusercontent.com/assets/30694/7899665/20db25b4-072d-11e5-9365-a73972236a3c.png)

**Comment by MichelvanderAa** [comment]
wat is de resolutie en bitrate van deze movie?

**Comment by MichelvanderAa** [comment]
I've WeTransfered a new video to you. 1400 pixels high , only slightly bigger and much better quality

**Comment by robbert** [comment]
I haven't received anything yet.

**Comment by robbert** [comment]
Oh, it's actually there, way back in time at 10:15.

**Comment by MichelvanderAa** [comment]
done √
