### ISSUE TITLE
Prevent kids from bursting out in tears

### ISSUE THREAD

**Issue by robbert** [robbert/book-of-sand#71]
![screen shot 2015-05-30 at 15 58 14](https://cloud.githubusercontent.com/assets/30694/7897699/735c3d98-06e5-11e5-9814-ff6ee52ab97f.png)

**Comment by MichelvanderAa** [comment]
Mature/Suggestive themes -  Infrequent mild
Horror/Fear Themes - Infrequent mild

waar komt hij dan op uit?

**Comment by robbert** [comment]
![screen shot 2015-05-30 at 16 21 51](https://cloud.githubusercontent.com/assets/30694/7897748/0d1de916-06e8-11e5-8532-ebe0c356fb34.png)
