### ISSUE TITLE
App: explanation box in beginning is too small

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#77]
"to choose etc" is too small to read. Also the sentences break in a weird way (for example 'keys' is listed on one row)

**Comment by Yolijn** [comment]
Fixed by replacing tutorial with swipe hint. Tutorial text wasn't fitting for mobile, this seems more inviting
![screen shot 2015-05-30 at 18 39 14](https://cloud.githubusercontent.com/assets/877246/7898270/3927a714-06fb-11e5-82f8-db8e3597d4d6.png)

**Comment by MichelvanderAa** [comment]
It's rather subtle like this. Maybe use some 'white' as rest and clear arrows

**Comment by robbert** [comment]
Actually they're 'glowing'! So this is the minimum state, white is the maximum state.

**Comment by MichelvanderAa** [comment]
sweetness!
