### ISSUE TITLE
App: audio looses sync (also inbetween tracks) when leaving text menu

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#81]

**Comment by MichelvanderAa** [comment]
probleem zit nog steeds in versie 0.03.   audio afwijking staat op +-45.48 als ik uit menu kom

**Comment by robbert** [comment]
Welkom in de wondere wereld van *one line fixes*...

![screen shot 2015-05-30 at 21 37 23](https://cloud.githubusercontent.com/assets/30694/7899086/51521d4a-0716-11e5-9cdb-48b28f018b60.png)

**Comment by MichelvanderAa** [comment]
coolio ;-)

**Comment by MichelvanderAa** [comment]
fixed √
