### ISSUE TITLE
*^@#%&@*#    ->  toch nog een credit verandering

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#83]
Sorry, don't kill the messenger...
Onder hf en sydney op loading screen toch:

co-sponsored by 
GOOGLE CULTURAL INSTITUTE

developed in association with
THE SPACE

Zelfde geldt voor app...

**Comment by MichelvanderAa** [comment]
Jochem heeft ze vanmorgen de link naar de beta website gestuurd. Ik denk dat ze het zo tof vinden dat ze zichtbaardere credit willen. Dus we zullen het maar als compliment zien...

**Comment by Yolijn** [comment]
Done for desktop, not sure about the extra content on mobile... do we want the last credits page to have smaller sized text so these extra credits will fit?

![screen shot 2015-05-30 at 19 58 53](https://cloud.githubusercontent.com/assets/877246/7898644/691b594c-0706-11e5-83bd-b38d00aaf90a.png)

**Comment by MichelvanderAa** [comment]
what if we would put Borges and me on page 1, would the credits then fit on page 3?

**Comment by Yolijn** [comment]
Done!
In the credits The Space is named BBC The Space, we currently only name The Space in the Splash-screens is that right?

![screen shot 2015-05-30 at 21 11 40](https://cloud.githubusercontent.com/assets/877246/7898934/7fd04562-0710-11e5-8b81-0892534589bd.png)

![screen shot 2015-05-30 at 21 10 23](https://cloud.githubusercontent.com/assets/877246/7898933/7fb0d9fc-0710-11e5-8cb2-121a2bc1e385.png)

**Comment by MichelvanderAa** [comment]
yes on loading screen we only call them The Space

See my comment about slightly slower speed of the pages in one of the other threads..

**Comment by Yolijn** [comment]
Ok, done!
