### ISSUE TITLE
App loading screen

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#84]
het voelt een beetje vreemd nu ze zo los gekoppeld zijn dat er geen werkbeschrijving bij mij en de uitvoerders staat (in kleine letters zoals bij commissioners)

Kan je hier van maken:

music, film, direction
Michel van der Aa 
--
mezzo-soprano
Kate Miller-Heidke

choir
Nederlands Kamerkoor

**Comment by Yolijn** [comment]
Done!

![screen shot 2015-05-30 at 19 52 42](https://cloud.githubusercontent.com/assets/877246/7898616/8463c1ae-0705-11e5-9fab-e77b478b0532.png)
![screen shot 2015-05-30 at 19 53 02](https://cloud.githubusercontent.com/assets/877246/7898615/846358fe-0705-11e5-8b14-783a90341037.png)

**Comment by MichelvanderAa** [comment]
Staat mijn naam wel horizontaal gecentreerd?

**Comment by Yolijn** [comment]
Jup, zie: http://beta.bookofsand.nl/latest/iphone.html was gewoon een slordige screenshot

**Comment by MichelvanderAa** [comment]
Ik denk dat elke pagina een halve seconde langer moet staan, en de pagina met de commissioner credits een seconde langer

**Comment by Yolijn** [comment]
Done
