### ISSUE TITLE
App: navigator doesn't dissapear

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#85]
of was dat al gefixt in de nieuwe code?

**Comment by robbert** [comment]
Ook in 0.0.3?

**Comment by MichelvanderAa** [comment]
als de navigator in beeld staat en je swipet dan gaat hij niet meer weg. Of is was dat ding dat niet op te lossen is? 
 In dat geval zou het goed zijn om met een tap op het scherm de navigatie weg te faden, zie ook ander punt in issue lijst

**Comment by robbert** [comment]
Fixed toch? Improving tap to hide controls is #89.
