### ISSUE TITLE
App (v004): only plays one audio track (top one)

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#95]

**Comment by MichelvanderAa** [comment]
de grootte van v004 bij mij is 132 MB, de vorige versie was 299 MB, ontbraken de 2 audio tracks niet gewoon in de app?

**Comment by robbert** [comment]
Dat zal het zijn geweest.

Hier is de nieuwe:

[Book of Sand 0.0.5](http://beta.bookofsand.nl/app/0.0.5.ipa)

Het is mijn development versie, ben nog aan het klooien met die "tap to hide" en dat werkt nog helemaal niet nu.
