### ISSUE TITLE
And yet another credit addition....Yolijn

### ISSUE THREAD

**Issue by MichelvanderAa** [robbert/book-of-sand#98]
Yolijn, kan je jezelf ergens bij de credits zetten?  Bij de web dev, of op zijn minst bij de "special thank to"s

Kan je ook aan de "special thanks to" toevoegen: Ruth Mackenzie (zet haar maar als eerste).

En:  Sophie Motley

thx

**Comment by robbert** [comment]
Done.

Heb uit verveling een linkje naar Ruth's Twitter toegevoegd.
